AdcCalibrationDataMap = { 2*50(float32 => float32) }

AdcChannelConfig = [
  interpolation_method: uint,
  ? calibration_table: AdcCalibrationDataMap
]

AdcConfig = [
  samples: uint,
  adc_channels_config: [*AdcChannelConfig]
]
