SensorMetadataConfig = [
  name: tstr,
  unit: tstr,
  ? description: tstr
]

SensorCalibrationDataMap = { 2*50(float => float) }

SensorConfigurationConfig = [
  type: uint,
  ? channel: uint,
  ? sampling_rate_ms: uint,
  ? calibration_table: SensorCalibrationDataMap,
  interpolation_method: uint,
  ? expression: tstr
]

SensorConfig = [
  id: tstr,
  metadata: SensorMetadataConfig,
  configuration: SensorConfigurationConfig
]

SensorsConfig = [
  sensors: [*SensorConfig]
]