ComUserConfig = [
  device_id: uint .size 8,
  server_id: uint,
  refresh_rate_ms: uint
]

CanbusConfig = [
  bus_channel: uint,
  bitrate: uint,
  sampling_point_percent: uint
]

SystemConfig = [
  device_id: uint .size 8,
  hw_version: uint,
  sw_version: uint,
  build_number: uint,
  com_users: [0*8 ComUserConfig],
  canbus_configs: [0*8 CanbusConfig]
]
