services:
  zephyr-dev:
    container_name: eerie_leap
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      - DISPLAY=:0
    volumes:
      - /dev/bus/usb:/dev/bus/usb:rw,rshared
      - ./:/home/ubuntu/zephyr/workspace/project:cached
      - ${HOME}/.Xauthority:/home/ubuntu/.Xauthority:ro
    ports:
      - "5900:5900"
      - "8080:8080"
    tty: true
    privileged: true
    pid: host
