CborCanMessageConfig = [
  frame_id: uint,
  send_interval_ms: uint,
  script_path: tstr
]

CborCanChannelConfig = [
  type: uint,
  bus_channel: uint,
  bitrate: uint,
  dbc_file_path: tstr,
  message_configs: [*CborCanMessageConfig]
]

CborCanbusConfig = [
  channel_configs: [0*8 CborCanChannelConfig],

  json_config_checksum: uint
]
