CborSensorLoggingConfig = [
  sensor_id_hash: uint,

  is_enabled: bool,
  log_raw_value: bool,
  log_only_new_data: bool
]

CborLoggingConfig = [
  logging_interval_ms: uint,
  max_log_size_mb: uint,
  sensor_configs: [*CborSensorLoggingConfig],

  json_config_checksum: uint
]
