SensorMetadataConfig = [
  name: tstr,
  unit: tstr,
  description: tstr
]

SensorCalibrationDataMap = { 2*50(float32 => float32) }

SensorConfigurationConfig = [
  type: uint,
  sampling_rate_ms: uint,
  interpolation_method: uint,
  ? channel: uint,
  ? calibration_table: SensorCalibrationDataMap,
  ? expression: tstr
]

SensorConfig = [
  id: tstr,
  id_hash: uint,
  metadata: SensorMetadataConfig,
  configuration: SensorConfigurationConfig
]

SensorsConfig = [
  sensors: [*SensorConfig]
]
